# docker build -t globalchange-crawler -f Dockerfile.globalchange .
# docker run globalchange-crawler

FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

COPY globalchange_crawler.py .

# Install the dependencies
RUN pip install scrapy azure-storage-blob

CMD ["python", "-u", "globalchange_crawler.py"]