# docker build -t carb-crawler -f Dockerfile.carb .
# docker run carb-crawler

FROM python:3.9-slim

WORKDIR /app

COPY carb_crawler.py .

RUN pip install scrapy azure-storage-blob

CMD ["python", "-u", "carb_crawler.py"]
