# docker build -t dot-crawler -f Dockerfile.dot .
# docker run dot-crawler

FROM python:3.9-slim

WORKDIR /app

COPY dot_crawler.py .

RUN pip install scrapy azure-storage-blob

CMD ["python", "-u", "dot_crawler.py"]
